import localFont from "next/font/local";
import "./globals.css";
import { Mulish } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const mulish = Mulish({
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"scroll-smooth"}>
      <body className={`${mulish.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
